# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'twin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntwin.proto\x12\x04twin\"\x94\x01\n\x0f\x43\x61ndidateAction\x12\x13\n\x0b\x61\x63tion_type\x18\x01 \x01(\t\x12\x39\n\nparameters\x18\x02 \x03(\x0b\x32%.twin.CandidateAction.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xc5\x01\n\x0fSimulateRequest\x12(\n\tcandidate\x18\x01 \x01(\x0b\x32\x15.twin.CandidateAction\x12>\n\rcurrent_state\x18\x02 \x03(\x0b\x32\'.twin.SimulateRequest.CurrentStateEntry\x12\x13\n\x0b\x63urrent_mse\x18\x03 \x01(\x02\x1a\x33\n\x11\x43urrentStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xe8\x01\n\x10SimulateResponse\x12\x15\n\rprojected_mse\x18\x01 \x01(\x02\x12\x17\n\x0fimprovement_pct\x18\x02 \x01(\x02\x12\x10\n\x08\x61pproved\x18\x03 \x01(\x08\x12\x16\n\x0erecommendation\x18\x04 \x01(\t\x12\x43\n\x0fprojected_state\x18\x05 \x03(\x0b\x32*.twin.SimulateResponse.ProjectedStateEntry\x1a\x35\n\x13ProjectedStateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32P\n\x0b\x44igitalTwin\x12\x41\n\x0eSimulateAction\x12\x15.twin.SimulateRequest\x1a\x16.twin.SimulateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANDIDATEACTION_PARAMETERSENTRY']._loaded_options = None
  _globals['_CANDIDATEACTION_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATEREQUEST_CURRENTSTATEENTRY']._loaded_options = None
  _globals['_SIMULATEREQUEST_CURRENTSTATEENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATERESPONSE_PROJECTEDSTATEENTRY']._loaded_options = None
  _globals['_SIMULATERESPONSE_PROJECTEDSTATEENTRY']._serialized_options = b'8\001'
  _globals['_CANDIDATEACTION']._serialized_start=21
  _globals['_CANDIDATEACTION']._serialized_end=169
  _globals['_CANDIDATEACTION_PARAMETERSENTRY']._serialized_start=120
  _globals['_CANDIDATEACTION_PARAMETERSENTRY']._serialized_end=169
  _globals['_SIMULATEREQUEST']._serialized_start=172
  _globals['_SIMULATEREQUEST']._serialized_end=369
  _globals['_SIMULATEREQUEST_CURRENTSTATEENTRY']._serialized_start=318
  _globals['_SIMULATEREQUEST_CURRENTSTATEENTRY']._serialized_end=369
  _globals['_SIMULATERESPONSE']._serialized_start=372
  _globals['_SIMULATERESPONSE']._serialized_end=604
  _globals['_SIMULATERESPONSE_PROJECTEDSTATEENTRY']._serialized_start=551
  _globals['_SIMULATERESPONSE_PROJECTEDSTATEENTRY']._serialized_end=604
  _globals['_DIGITALTWIN']._serialized_start=606
  _globals['_DIGITALTWIN']._serialized_end=686
# @@protoc_insertion_point(module_scope)
