apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "astra-xapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "astra-xapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "astra-xapp.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "astra-xapp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ASTRA_MODE
              value: {{ .Values.env.ASTRA_MODE | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
