global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'astra_xapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['astra:8000']
  - job_name: 'open5gs_kpi_exporter'
    metrics_path: '/'
    static_configs:
      - targets: ['kpi-exporter:9090']
