"""create_initial_audit_tables

Revision ID: 63f36ab2192d
Revises:
Create Date: 2026-06-11 17:47:34.114631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63f36ab2192d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'astra_event_audit',
        sa.Column('id', sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column('cell_id', sa.String(length=128), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('correlation_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_astra_event_audit')
    )

    # Indexes for common queries
    op.create_index('idx_astra_audit_cell_id', 'astra_event_audit', ['cell_id'], unique=False)
    op.create_index('idx_astra_audit_event_type', 'astra_event_audit', ['event_type'], unique=False)
    op.create_index('idx_astra_audit_timestamp', 'astra_event_audit', ['timestamp'], unique=False)
    op.create_index('idx_astra_audit_correlation_id', 'astra_event_audit', ['correlation_id'], unique=False)
    op.create_index('idx_astra_audit_cell_type_time', 'astra_event_audit', ['cell_id', 'event_type', 'timestamp'], unique=False)
    op.create_index('idx_astra_audit_cell_time', 'astra_event_audit', ['cell_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_astra_audit_cell_time', table_name='astra_event_audit')
    op.drop_index('idx_astra_audit_cell_type_time', table_name='astra_event_audit')
    op.drop_index('idx_astra_audit_correlation_id', table_name='astra_event_audit')
    op.drop_index('idx_astra_audit_timestamp', table_name='astra_event_audit')
    op.drop_index('idx_astra_audit_event_type', table_name='astra_event_audit')
    op.drop_index('idx_astra_audit_cell_id', table_name='astra_event_audit')
    op.drop_table('astra_event_audit')
    # ### end Alembic commands ###